In [1]:
import numpy as np

In [4]:
nn_ls_list = np.loadtxt("results/nn_ls_simulation_study.csv")

In [15]:
rkhs_kl_list = np.loadtxt("results/nn_kl_IHDP.csv")
rkhs_tl_list = np.loadtxt("results/nn_tl_IHDP.csv")


In [17]:
rkhs_kl_list

array([[ 1.76921427e+00,  3.47241362e+01,  6.99139019e+00,
         1.74234140e+00,  1.79608715e+00, -4.61782463e+00,
         7.40660971e+01, -9.97196450e+00,  2.39547449e+01],
       [ 1.44210026e-01,  8.77653241e-01, -8.77568996e-02,
         8.78655016e-02,  2.00554550e-01,  3.21859379e-01,
         1.43344710e+00, -1.43687218e+00,  1.26135838e+00],
       [ 1.38177323e+00,  1.31991185e+01,  1.20260716e+01,
         1.34259200e+00,  1.42095447e+00, -2.97660659e+00,
         2.93748436e+01, -8.65031501e+00,  3.27024583e+01],
       [ 4.56289023e-01,  4.00664537e+01,  1.85067705e+02,
         3.92752767e-01,  5.19825280e-01, -1.54520374e+01,
         9.55849448e+01, -1.51527841e+02,  5.21663251e+02],
       [ 1.24379849e+00,  2.60156034e+01,  1.02253544e+01,
         1.20207465e+00,  1.28552234e+00, -4.91267528e+00,
         5.69438821e+01, -2.85693068e+00,  2.33076395e+01],
       [ 1.67870879e-01,  1.42167278e+00, -7.04650809e-01,
         1.03027157e-01,  2.32714593e-01,  5.595174

In [11]:
np.mean((nn_kl_list - 5)[:, 0:3]**2, axis=0)

array([0.35137789, 0.32087267, 0.07059225])

In [13]:
np.mean((nn_tl_list - 5)[:, 0:3]**2, axis=0)

array([0.34534787, 0.31518418, 0.06935933])