In [46]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [47]:
from ddml import *

In [54]:
import glob
from utils.ihdp_data import *
from sklearn.preprocessing import StandardScaler


data_base_dir = "./data/IHDP/sim_data_redraw_T"
simulation_files = sorted(glob.glob("{}/*.csv".format(data_base_dir)))
  
# Simulation parameters
exp_name = "IHDP"
np.random.seed(0)

data_base_dir = "./data/IHDP/sim_data_redraw_T"
simulation_files = sorted(glob.glob("{}/*.csv".format(data_base_dir)))

# Generate covariates
np.random.seed(0)

true_ATEs_list = []

nn_ls_list = []
nn_ls_logit_list = []
nn_kl_list = []
nn_tl_list = []
nn_mle_list = []

rkhs_ls_list = []
rkhs_kl_list = []
rkhs_tl_list = []
rkhs_mle_list = []

result_list = []

for tr in range(len(simulation_files)):
    print("tr", tr)
    simulation_file = simulation_files[tr]
    x = load_and_format_covariates(simulation_file, delimiter=' ')
    t, y, y_cf, mu_0, mu_1 = load_other_stuff(simulation_file, delimiter=' ')
    X = np.c_[t, x]
    true_ATE = np.mean(mu_1 - mu_0)
    true_ATEs_list.append(true_ATE)

    y_scaler = StandardScaler(with_mean=True).fit(y)
    y = y_scaler.transform(y)
    
    covariates = x
    treatment = t.T[0]
    outcome = y.T[0]
    
    # Below, we conduct each method to estimate the ATE

    ############################

    cross_fitting_folds=2

    method = "NN_RieszLearner"

    riesz_hidden_dim= 100
    reg_hidden_dim= 100
    riesz_max_iter = 100
    reg_max_iter = 100


    riesz_loss = "LS"
    riesz_with_D = True
    riesz_link_name = "Linear"

    dd_ate = DDML_ATE()
    result = dd_ate.estimate(covariates, treatment, 
                    outcome, method=method, 
                    cross_fitting_folds = cross_fitting_folds,
                    riesz_loss=riesz_loss, 
                    riesz_with_D=riesz_with_D, 
                    riesz_link_name=riesz_link_name, 
                    riesz_hidden_dim=riesz_hidden_dim, 
                    reg_hidden_dim=reg_hidden_dim,
                    riesz_max_iter=riesz_max_iter, 
                    reg_max_iter=reg_max_iter)

    nn_ls_list.append(result)

    riesz_loss = "KL"
    riesz_with_D = False
    riesz_link_name = "Logit"

    dd_ate = DDML_ATE()
    result = dd_ate.estimate(covariates, treatment, 
                    outcome, method=method, 
                    cross_fitting_folds = cross_fitting_folds,
                    riesz_loss=riesz_loss, 
                    riesz_with_D=riesz_with_D, 
                    riesz_link_name=riesz_link_name, 
                    riesz_hidden_dim=riesz_hidden_dim, 
                    reg_hidden_dim=reg_hidden_dim,
                    riesz_max_iter=riesz_max_iter, 
                    reg_max_iter=reg_max_iter)

    nn_kl_list.append(result)


    riesz_loss = "TL"
    riesz_with_D = False
    riesz_link_name = "Logit"

    dd_ate = DDML_ATE()
    result = dd_ate.estimate(covariates, treatment, 
                    outcome, method=method, 
                    cross_fitting_folds = cross_fitting_folds,
                    riesz_loss=riesz_loss, 
                    riesz_with_D=riesz_with_D, 
                    riesz_link_name=riesz_link_name, 
                    riesz_hidden_dim=riesz_hidden_dim, 
                    reg_hidden_dim=reg_hidden_dim,
                    riesz_max_iter=riesz_max_iter, 
                    reg_max_iter=reg_max_iter)

    nn_tl_list.append(result)

    riesz_loss = "MLE"
    riesz_with_D = False
    riesz_link_name = "Logit"

    dd_ate = DDML_ATE()
    result = dd_ate.estimate(covariates, treatment, 
                    outcome, method=method, 
                    cross_fitting_folds = cross_fitting_folds,
                    riesz_loss=riesz_loss, 
                    riesz_with_D=riesz_with_D, 
                    riesz_link_name=riesz_link_name, 
                    riesz_hidden_dim=riesz_hidden_dim, 
                    reg_hidden_dim=reg_hidden_dim,
                    riesz_max_iter=riesz_max_iter, 
                    reg_max_iter=reg_max_iter)

    nn_mle_list.append(result)

    
    np.savetxt("results2/true_ATEs_%s.csv"%exp_name, true_ATEs_list)
    np.savetxt("results2/nn_ls_%s.csv"%exp_name, nn_ls_list)
    np.savetxt("results2/nn_kl_%s.csv"%exp_name, nn_kl_list)
    np.savetxt("results2/nn_tl_%s.csv"%exp_name, nn_tl_list)
    np.savetxt("results2/nn_mle_%s.csv"%exp_name, nn_mle_list)
    #np.savetxt("results2/rkhs_ls_%s.csv"%exp_name, rkhs_ls_list)
    #np.savetxt("results2/rkhs_kl_%s.csv"%exp_name, rkhs_kl_list)
    #np.savetxt("results2/rkhs_tl_%s.csv"%exp_name, rkhs_tl_list)
    #np.savetxt("results2/rkhs_mle_%s.csv"%exp_name, rkhs_mle_list)

tr 0
tr 1
tr 2
tr 3
tr 4
tr 5
tr 6
tr 7
tr 8
tr 9
tr 10
tr 11
tr 12
tr 13
tr 14
tr 15
tr 16
tr 17
tr 18
tr 19
tr 20
tr 21
tr 22
tr 23
tr 24
tr 25
tr 26
tr 27
tr 28
tr 29
tr 30
tr 31
tr 32
tr 33
tr 34
tr 35
tr 36
tr 37
tr 38
tr 39
tr 40
tr 41
tr 42
tr 43
tr 44
tr 45
tr 46
tr 47
tr 48
tr 49
tr 50
tr 51
tr 52
tr 53
tr 54
tr 55
tr 56
tr 57
tr 58
tr 59
tr 60
tr 61
tr 62
tr 63
tr 64
tr 65
tr 66
tr 67
tr 68
tr 69
tr 70
tr 71
tr 72
tr 73
tr 74
tr 75
tr 76
tr 77
tr 78
tr 79
tr 80
tr 81
tr 82
tr 83
tr 84
tr 85
tr 86
tr 87
tr 88
tr 89
tr 90
tr 91
tr 92
tr 93
tr 94
tr 95
tr 96
tr 97
tr 98
tr 99


In [5]:
print(nn_ls_list)
print(nn_kl_list)
print(nn_tl_list)

[(np.float32(1.7688495), np.float64(2.225919430374844), np.float64(1.8087304346082567), np.float32(1.7468145), np.float32(1.7908845), np.float64(1.8712774117357909), np.float64(2.580561449013897), np.float64(1.6627358863771113), np.float64(1.954724982839402))]
[(np.float32(1.7703034), np.float64(14.104529865239812), np.float64(1.196257429420085), np.float32(1.7466137), np.float32(1.793993), np.float64(1.9662901796004277), np.float64(26.242769550879196), np.float64(-3.1205169976174756), np.float64(5.513031856457646))]
[(np.float32(1.7653139), np.float64(12.909599819558808), np.float64(4.2347122727695234), np.float32(1.7405006), np.float32(1.7901272), np.float64(1.2987809716349652), np.float64(24.52041866748265), np.float64(-1.9329817728045624), np.float64(10.402406318343608))]


In [6]:
riesz_loss = "KL"
riesz_with_D = False
riesz_link_name = "Logit"

dd_ate = DDML_ATE()
result = dd_ate.estimate(covariates, treatment, 
                outcome, method=method, 
                cross_fitting_folds = cross_fitting_folds,
                riesz_loss=riesz_loss, 
                riesz_with_D=riesz_with_D, 
                riesz_link_name=riesz_link_name, 
                riesz_hidden_dim=riesz_hidden_dim, 
                reg_hidden_dim=reg_hidden_dim,
                riesz_max_iter=riesz_max_iter, 
                reg_max_iter=reg_max_iter)

nn_kl_list.append(result)

In [10]:
np.mean(dd_ate.IPW_score)

np.float64(2.0010835236939277)

In [11]:
dd_ate.IPW_est

np.float64(2.0010835236939277)

In [12]:
nn_kl_list

[(np.float32(1.7703034),
  np.float64(14.104529865239812),
  np.float64(1.196257429420085),
  np.float32(1.7466137),
  np.float32(1.793993),
  np.float64(1.9662901796004277),
  np.float64(26.242769550879196),
  np.float64(-3.1205169976174756),
  np.float64(5.513031856457646)),
 (np.float64(1.2918530989705599),
  np.float64(2.0010835236939277),
  np.float64(1.3278598644194228),
  np.float64(0.9763731492292722),
  np.float64(1.6073330487118476),
  np.float64(1.696474058473641),
  np.float64(2.3056929889142146),
  np.float64(0.5331792515935025),
  np.float64(2.122540477245343))]

In [55]:
true_ATEs_list = np.array(true_ATEs_list)

nn_ls_list = np.array(nn_ls_list)
nn_kl_list = np.array(nn_kl_list)
nn_tl_list = np.array(nn_tl_list)
nn_mle_list = np.array(nn_mle_list)

rkhs_ls_list = np.array(rkhs_ls_list)
rkhs_kl_list = np.array(rkhs_kl_list)
rkhs_tl_list = np.array(rkhs_tl_list)
rkhs_mle_list = np.array(rkhs_mle_list)

In [9]:
true_conf_list = [np.mean((true_list[:, 3] <= 5) * (5 <= true_list[:, 4])), np.mean((true_list[:, 5] <= 5) * (5 <= true_list[:, 6])), np.mean((true_list[:, 7] <= 5) * (5 <= true_list[:, 8]))]
nn_ls_conf_list = [np.mean((nn_ls_list[:, 3] <= 5) * (5 <= nn_ls_list[:, 4])), np.mean((nn_ls_list[:, 5] <= 5) * (5 <= nn_ls_list[:, 6])), np.mean((nn_ls_list[:, 7] <= 5) * (5 <= nn_ls_list[:, 8]))]
nn_kl_conf_list = [np.mean((nn_kl_list[:, 3] <= 5) * (5 <= nn_kl_list[:, 4])), np.mean((nn_kl_list[:, 5] <= 5) * (5 <= nn_kl_list[:, 6])), np.mean((nn_kl_list[:, 7] <= 5) * (5 <= nn_kl_list[:, 8]))]
nn_tl_conf_list = [np.mean((nn_tl_list[:, 3] <= 5) * (5 <= nn_tl_list[:, 4])), np.mean((nn_tl_list[:, 5] <= 5) * (5 <= nn_tl_list[:, 6])), np.mean((nn_tl_list[:, 7] <= 5) * (5 <= nn_tl_list[:, 8]))]
nn_mle_conf_list = [np.mean((nn_mle_list[:, 3] <= 5) * (5 <= nn_mle_list[:, 4])), np.mean((nn_mle_list[:, 5] <= 5) * (5 <= nn_mle_list[:, 6])), np.mean((nn_mle_list[:, 7] <= 5) * (5 <= nn_mle_list[:, 8]))]
rkhs_ls_conf_list = [np.mean((rkhs_ls_list[:, 3] <= 5) * (5 <= rkhs_ls_list[:, 4])), np.mean((rkhs_ls_list[:, 5] <= 5) * (5 <= rkhs_ls_list[:, 6])), np.mean((rkhs_ls_list[:, 7] <= 5) * (5 <= rkhs_ls_list[:, 8]))]
rkhs_kl_conf_list = [np.mean((rkhs_kl_list[:, 3] <= 5) * (5 <= rkhs_kl_list[:, 4])), np.mean((rkhs_kl_list[:, 5] <= 5) * (5 <= rkhs_kl_list[:, 6])), np.mean((rkhs_kl_list[:, 7] <= 5) * (5 <= rkhs_kl_list[:, 8]))]
rkhs_tl_conf_list = [np.mean((rkhs_tl_list[:, 3] <= 5) * (5 <= rkhs_tl_list[:, 4])), np.mean((rkhs_tl_list[:, 5] <= 5) * (5 <= rkhs_tl_list[:, 6])), np.mean((rkhs_tl_list[:, 7] <= 5) * (5 <= rkhs_tl_list[:, 8]))]
rkhs_mle_conf_list = [np.mean((rkhs_mle_list[:, 3] <= 5) * (5 <= rkhs_mle_list[:, 4])), np.mean((rkhs_mle_list[:, 5] <= 5) * (5 <= rkhs_mle_list[:, 6])), np.mean((rkhs_mle_list[:, 7] <= 5) * (5 <= rkhs_mle_list[:, 8]))]


array([-2.42299062, -2.07265151, -2.9226657 , -4.70825222, -2.99039754,
       -3.08153206, -2.25861665, -3.0712883 , -1.93997705, -2.94672507,
       -2.08092835, -2.59767623, -2.00604527, -2.62241832, -3.95149084,
       -2.63801159, -6.25556438, -3.48857109, -5.05649229, -3.95749362,
       -2.66045059, -2.30201672, -2.81959048, -2.52164621, -2.26775816,
       -2.35395921, -1.95540787, -2.52061621, -3.56961121, -5.80499626,
       -2.8479524 , -2.88334741, -3.37449256, -4.82413798, -2.08066315,
       -3.82671144, -3.74897197, -2.58340128, -2.62310103, -3.005224  ,
       -7.25851285, -3.91399331, -2.55027767, -2.21367007, -3.11028957,
       -7.5576143 , -3.30867234, -2.35710113, -2.2996834 , -3.43229734,
       -3.69641671, -3.42212978, -2.17662325, -2.04152257, -2.58566642,
       -3.36900999, -2.22433701, -2.90086717, -2.35279767, -2.75770772,
       -2.8397682 , -2.02299951, -3.15151054, -3.9498426 , -2.89759599,
       -2.84811217, -2.67060357, -2.25360936, -1.98571957, -3.97

In [56]:
np.mean((nn_ls_list[:, 0:3] - np.array([true_ATEs_list]*3).T[:len(nn_ls_list)])**2, axis=0)


array([11.54139371,  9.54419308, 11.48552392])

In [58]:
np.mean((nn_kl_list[:, 0:3] - np.array([true_ATEs_list]*3).T[:len(nn_kl_list)])**2, axis=0)

array([11.54759574,  8.47092358, 11.48512257])

In [59]:
np.mean((nn_tl_list[:, 0:3] - np.array([true_ATEs_list]*3).T[:len(nn_tl_list)])**2, axis=0)

array([11.54029683,  8.622344  , 11.50127299])

In [27]:
nn_tl_list

array([[ 1.74407065e+00,  4.16816537e+01,  2.84249302e+01,
         1.72013569e+00,  1.76800561e+00, -1.81152890e+01,
         1.01478596e+02, -1.95837684e+01,  7.64336288e+01],
       [ 1.78441107e-01,  2.39032752e-01, -5.69248423e-02,
         1.23453088e-01,  2.33429134e-01,  1.13783909e-01,
         3.64281594e-01, -6.19484610e-01,  5.05634925e-01],
       [ 1.40070915e+00,  5.08488407e+00,  4.97156765e+00,
         1.36454666e+00,  1.43687165e+00, -4.45973025e-01,
         1.06157412e+01, -1.26103116e+00,  1.12041665e+01],
       [ 4.75775003e-01,  1.09038921e+00,  3.79103522e-01,
         4.11718428e-01,  5.39831579e-01,  6.73644678e-01,
         1.50713373e+00, -1.94083141e-01,  9.52290185e-01],
       [ 1.23640430e+00,  3.48177639e+00,  2.03931994e+00,
         1.19980502e+00,  1.27300358e+00,  1.20527501e+00,
         5.75827777e+00,  6.66243117e-01,  3.41239677e+00],
       [ 1.79048121e-01,  6.40407894e-01,  6.22919420e-01,
         1.15246445e-01,  2.42849797e-01,  1.445348

In [60]:
np.mean((nn_tl_list[:, 0:3] - np.array([true_ATEs_list]*3).T)**2, axis=0)

array([11.54029683,  8.622344  , 11.50127299])

In [61]:
np.mean((nn_mle_list[:, 0:3] - np.array([true_ATEs_list]*3).T)**2, axis=0)

array([11.5523536 , 11.71553957, 11.52002202])

In [62]:
np.mean((nn_mle_list[:, 0:3] - np.array([true_ATEs_list]*3).T)**2, axis=0)

array([11.5523536 , 11.71553957, 11.52002202])

In [63]:
np.mean((nn_kl_list[:, 0:3] - np.array([true_ATEs_list]*3).T)**2, axis=0)

array([11.54759574,  8.47092358, 11.48512257])

In [65]:
np.mean((rkhs_ls_list[:, 0:3] - np.array([true_ATEs_list]*3).T)**2, axis=0)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [67]:
true_ATEs_list

array([4.19061929, 2.21867106, 4.36578046, 5.15550452, 4.23515674,
       3.25911059, 3.89980253, 3.50141106, 3.95803369, 3.53677565,
       3.91925338, 3.95697207, 4.0492634 , 2.88052387, 4.46885457,
       4.15143145, 6.62991237, 4.11355989, 5.54867359, 4.93824037,
       4.1093892 , 2.37113283, 3.03489245, 4.18631512, 3.27394799,
       2.95040143, 3.92152335, 3.03656141, 3.97523688, 6.37835307,
       4.48636285, 3.9077722 , 4.09318224, 5.5913192 , 4.05232508,
       4.73073735, 4.75426856, 4.00815232, 4.22686211, 4.17225219,
       7.87664592, 4.74549789, 4.18124934, 4.1508128 , 4.46677005,
       8.18767045, 4.06630752, 4.14114241, 3.97812599, 4.58832728,
       4.17367242, 4.51693573, 4.11473611, 4.06517846, 4.22027123,
       4.63698329, 3.84368709, 4.18401259, 4.16924409, 3.92231572,
       3.45770887, 3.9244933 , 3.89238764, 4.94429353, 4.49342595,
       3.93521053, 4.12558656, 3.94613535, 4.03249611, 4.24693152,
       4.33929104, 3.98203664, 4.26268879, 4.01412655, 4.11420